### ISSUE TITLE
How to handle CSS and images inside HTML string?

### ISSUE THREAD

**Issue by SergioCrisostomo** [bjrmatos/electron-html-to#453]
I am using the PDF converter and in the HTML string I'm passing I have things like:

    <head>
        <link rel="stylesheet" href="/css/pdf.css">
    </head>

and 

    <img src="/images/company_logo.jpg" title="MyLogo">

How to tell `electron-html-to` or Electron where to find those resources?

(And thanks for a useful project!)

**Comment by bjrmatos** [comment]
you will need to set the `allowLocalFilesAccess` option to `true` and request resources like this:

```html
<!-- index.html -->
<head>
    <link rel="stylesheet" href="file:///Volumes/DATA/workspace/electron-html-to-with-local-resources/css/pdf.css">
</head>
<body>
    <h1 class="title">It Works!!</h1>
    <img src="file:///Volumes/DATA/workspace/electron-html-to-with-local-resources/images/company_logo.jpg" title="MyLogo">
</body>
```

```css
/*pdf.css*/

.title {
  color: palevioletred;
}
```

```js
/*index.js*/

'use strict';

var fs = require('fs'),
    convertFactory = require('electron-html-to');

var conversion = convertFactory({
  converterPath: convertFactory.converters.PDF,
  allowLocalFilesAccess: true
});

conversion({
  html: fs.readFileSync('./index.html').toString()
}, function(err, result) {
  if (err) {
    conversion.kill();
    return console.error(err);
  }

  result.stream.pipe(fs.createWriteStream('output.pdf'));
  console.log('PDF is ready');
  conversion.kill();
});

```

of course if your html doesn't have url in the form of `file://path/to/you/base/public/directory` you would need to transform paths from `/images/company_logo.jpg` to `file://path/to/you/base/public/directory/images/company_logo.jpg`

demo:

![electron-html-to-with-local-resources](https://cloud.githubusercontent.com/assets/4262050/21965336/e6fd5464-db2b-11e6-8284-30c6bd3cd1d4.gif)

**Comment by SergioCrisostomo** [comment]
@bjrmatos thank you! will test it!

Should this be part of the docs somehow? if you want I can suggest som docs adition or make a `.MD` file with your instructions.

**Comment by bjrmatos** [comment]
yes! i would prefer a new section in the current README.md, something like "Using local resources".

PR are welcome 😄 tasks -> #454
